app:
  name: "Qwen-Assist-2-Test"
  description: "Multi-agent system built on the Qwen3 LLM (Test Mode)"
  version: "0.1.0"

llm:
  model: "qwen3-32b"
  model_server: "dashscope"
  api_key: "${DASHSCOPE_API_KEY}"
  generate_cfg:
    top_p: 0.8

# Disable MCP servers for testing
mcp_servers: {}

ui:
  port: 7860
  share: false
  title: "Qwen-Assist (Test Mode)"
  theme: "default"

routing:
  default_agent: "router"
  timeout: 60

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"